package com.blankzhu.v1.authorization;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.TimeZone;

import static com.blankzhu.v1.common.VaasPublicParamConstants.*;

public class AuthorizationGenerator {
    /**
     * generate authorization header
     *
     * @param accessKey     API access key
     * @param signedHeaders headers involved in signing, lower case concat in ';'
     * @param signature     signature generated by CtHmacSha256Signer
     * @return authorization header value
     */
    static public String generate(String accessKey,
                                  String signedHeaders,
                                  String signature,
                                  String timestamp) {
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat(YEAR_MONTH_DATE_FORMAT);
        simpleDateFormat.setTimeZone(TimeZone.getTimeZone("UTC"));
        String date = simpleDateFormat.format(new Date(Long.parseLong(timestamp + "000")));
        String credentialScope = String.format("%s/%s", date, CT_VAAS_PRODUCT_NAME);

        return String.format("%s Credential=%s/%s, SignedHeaders=%s, Signature=%s", CT_VAAS_SIGN_ALGORITHM, accessKey, credentialScope, signedHeaders, signature);
    }
}
